name: Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.1"]
        php-flavor: ["fpm", "cli", "apache"]
        node-version: ["14", "16"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ${{ matrix.php-flavor }} images for PHP ${{ matrix.php-version }} and NODE ${{ matrix.node-version }}
        run: |
          docker build . --file Dockerfile --tag php --build-arg TAG=${{ matrix.php-version }}-v4-${{ matrix.php-flavor }}
          docker build . --file Dockerfile --tag node --build-arg TAG=${{ matrix.php-version }}-v4-${{ matrix.php-flavor }}-node${{ matrix.node-version }}

      - name: Log into registries
        run: |
          # Login to Dockerhub.
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u verbral --password-stdin
          # Login to Github.
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin

      - name: Push ${{ matrix.php-flavor }} images for PHP ${{ matrix.php-version }} and NODE ${{ matrix.node-version }}
        run: |
          export TAG=${{ matrix.php-version }}-v4-${{ matrix.php-flavor }}
          docker tag php docker.io/verbral/docker-drupal:$TAG
          docker push docker.io/verbral/docker-drupal:$TAG
          export TAG=${{ matrix.php-version }}-v4-${{ matrix.php-flavor }}-node${{ matrix.node-version }}
          docker tag node docker.io/verbral/docker-drupal:$TAG
          docker push docker.io/verbral/docker-drupal:$TAG
