name: Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["7.4", "8.0", "8.1"]
        node-version: ["14"]
    env:
      IMAGE_NAME: docker-drupal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image verbral/docker-drupal:${{ matrix.php-version }}-v4-apache-node${{ matrix.node-version }}
        run: docker build . --file Dockerfile --tag image --build-arg PHP_VERSION=${{ matrix.php-version }} --build-arg NODE_VERSION=${{ matrix.node-version }}

      - name: Log into registries
        run: |
          # Login to Dockerhub.
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u verbral --password-stdin
          # Login to Github.
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin

      - name: Push image verbral/docker-drupal:${{ matrix.php-version }}-v4-apache-node${{ matrix.node-version }} to registry
        run: |
          # Push to Dockerhub.
          docker tag image docker.io/verbral/$IMAGE_NAME:${{ matrix.php-version }}-v4-apache-node${{ matrix.node-version }}
          docker push docker.io/verbral/$IMAGE_NAME:${{ matrix.php-version }}-v4-apache-node${{ matrix.node-version }}