name: Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.1"]
        php-flavor: ["fpm", "cli", "apache"]
        node-version: ["14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ${{ matrix.php-flavor }} images for PHP ${{ matrix.php-version }} and NODE ${{ matrix.node-version }}
        run: |
          IMAGE_NAME=php:${{ matrix.php-version }}-v4-${{ matrix.php-flavor }} docker build . --file Dockerfile --tag docker.io/verbral/docker-drupal:$IMAGE_NAME --build-arg IMAGE_NAME=$IMAGE_NAME
          IMAGE_NAME=php:${{ matrix.php-version }}-v4-${{ matrix.php-flavor }}-node${{ matrix.node-version }} docker build . --file Dockerfile --tag docker.io/verbral/docker-drupal:$IMAGE_NAME --build-arg IMAGE_NAME=$IMAGE_NAME


      - name: Log into registries
        run: |
          # Login to Dockerhub.
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u verbral --password-stdin
          # Login to Github.
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin

      - name: Push ${{ matrix.php-flavor }} images for PHP ${{ matrix.php-version }} and NODE ${{ matrix.node-version }}
        run: |
          IMAGE_NAME=php:${{ matrix.php-version }}-v4-${{ matrix.php-flavor }} docker push docker.io/verbral/$IMAGE_NAME
          IMAGE_NAME=php:${{ matrix.php-version }}-v4-${{ matrix.php-flavor }}-node${{ matrix.node-version }} docker push docker.io/verbral/$IMAGE_NAME